name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run test
        run: npm install; npm run build
        env:
          CI: False
          REACT_APP_APIKey: ${{ vars.REACT_APP_APIKey }}
          API_KEY: ${{ secrets.API_KEY }}
      - name: Run an online service (prod)
        run: echo  ${{ secrets.REACT_APP_APIKey }}
      - name: test2
        run: echo  ${{ vars.REACT_APP_APIKey }}
        env:
          REACT_APP_APIKey: ${{ vars.REACT_APP_APIKey }}
          API_KEY: ${{ secrets.API_KEY }}
