name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Run an online service (prod)
        run: echo  ${{ secrets.API_KEY }}
      - name: Run test
        run: echo  ${{ vars.KEY_TEST }}
        env:
          KEY_TEST: ${{ vars.KEY_TEST }}
          API_KEY: ${{ secrets.API_KEY }}
