name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run test
        run: npm install; npm run build
        env:
          CI: False
          REACT_APP_APIKey: ${{ vars.REACT_APP_APIKey }}
          API_KEY: ${{ secrets.API_KEY }}
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x  
      - name: Run Tests
        run: npm test --ci --silent --testPathIgnorePatterns=experimental
        env:
          CI: False
          REACT_APP_APIKey: ${{ vars.REACT_APP_APIKey }}
          API_KEY: ${{ secrets.API_KEY }}
